export const ACTION_FETCH_COURSES_DATA = 'ACTION_FETCH_COURSES_DATA';
export const ACTION_FETCH_IMAGES_LIST = 'ACTION_FETCH_IMAGES_LIST';
export const ACTION_SET_ACTIVE_COURSE_ID = 'ACTION_SET_ACTIVE_COURSE_ID';
export const ACTION_SHOW_DIALOG = 'ACTION_SHOW_DIALOG';
export const ACTION_CLOSE_DIALOG = 'ACTION_CLOSE_DIALOG';
// user click 'Add new course'
export const ACTION_COURSE_ADD = 'ACTION_COURSE_ADD';
// user click 'Save' on new course
export const ACTION_COURSE_CREATE = 'ACTION_COURSE_CREATE';
export const ACTION_COURSE_SAVE = 'ACTION_COURSE_SAVE';
export const ACTION_COURSE_DELETE = 'ACTION_COURSE_DELETE';
export const ACTION_IMAGE_UPLOAD = 'ACTION_IMAGE_UPLOAD';
export const ACTION_COURSE_ORDER = 'ACTION_COURSE_ORDER';
